config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'pages/home'



  namespace :admin do
    root to: 'dashboard#index'
    resources :subscriptions


  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  layout 'admin'
  def index
  end

end

app/controllers/admin/subscriptions_controller.rb
class Admin::SubscriptionsController < ApplicationController
  layout 'admin'
  
  def new
    @subscription = Subscription.new
  end

  def create
    @subscription = Subscription.new(subscription_params)
    @subscription.save
  end

  def index
    @subscriptions = Subscription.all
  end

  def show
     @subscription = Subscription.find(params[:id])
  end

  def edit
     @subscription = Subscription.find(params[:id])
  end

  def update
    @subscription = Subscription.find(params[:id])
    @subscription.update(subscription_params)
    render 'show'
  end

  def destroy
    @subscription = Subscription.find(params[:id])
    @subscription.destroy
    redirect_to admin_subscriptions_path
  end


  private
    def subscription_params
      params.require(:subscription).permit(
      :name,
      :tagline,
      :description,
      :price,
      :quantity
      )
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  ABOUT = [
    {
      title:"私だけの美味しいご褒美おやつ定期便",
      description: "1BOX 1,980円(税込、送料無料)で、4週間か2週間毎にお届けします。スキップやキャンセルも可能です。"
    },
    { title:"1,000億通りからセレクトされたおやつ",
      description: "毎月100種以上の季節感あるおやつ。お好みに合わせて1,000億通り以上から毎回8種セレクトします。"
    },
    { title:"Real Foodだからカラダに優しい",
      description: "カタチある自然素材(Real Food)から美味しさと栄養を。人工添加物、白砂糖、ショートニング不使用。"
    }

  ]
  def home
    @abouts = ABOUT
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/admin/dashboard/index.html.haml
%h1
  ="Welcome to the Admin Page"

app/views/admin/subscriptions/_form.html.haml
=bootstrap_form_for [:admin, @subscription], layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-8", :html => {"accept-charset" => "UTF-8"} do |f|
  = f.text_field :name
  = f.text_field :tagline
  = f.text_area :description
  = f.number_field :price
  = f.number_field :quantity

  = f.submit

app/views/admin/subscriptions/edit.html.haml
.row
  .col-sm-12
    .card.card-border.card-primary
      .card-header
        %h3.card-title
          ="Edit #{@subscription.name}"
      .card-body
        = render "form"

app/views/admin/subscriptions/index.html.haml
-@subscriptions.each do |subscription|
  .mx-auto{:style => "width: 800px"}
    .card.mb-3
      .row
        .col-md-4
          %img.card-img{:alt => "...", :src => "..."}/
        .col-md-8
          .card-body
            %h5.card-title
              =link_to subscription.name, admin_subscription_path(subscription)
            .card-text
              =subscription.tagline
            .card-text
              =subscription.description
            .card-text
              ="Price: #{subscription.price}"
            .card-text
              ="Quantity: #{subscription.quantity}"
.card-text
  .float-right.mr-5
    =link_to "Create", new_admin_subscription_path, class: 'm-3 btn-primary btn-lg'

app/views/admin/subscriptions/new.html.haml
.row
  .col-sm-12
    .card.card-border.card-primary
      .card-header
        %h3.card-title
          ='Create a New Subscription'
      .card-body
        = render "form"

app/views/admin/subscriptions/show.html.haml
.mx-auto{:style => "width: 800px"}
  .card.mb-3
    .row
      .col-md-4
        %img.card-img{:alt => "...", :src => "..."}/
      .col-md-8
        .card-body
          %h5.card-title
            =@subscription.name
          .card-text
            =@subscription.tagline
          .card-text
            =@subscription.description
          .card-text
            ="Price: #{@subscription.price}"
          .card-text
            ="Quantity: #{@subscription.quantity}"
  .mt-3
    .card-text
      =link_to "Edit", edit_admin_subscription_path, class: 'm-3 btn-primary btn-lg'
      =link_to "Delete", admin_subscription_path, method: :delete, class: 'm-3 btn-danger btn-lg'
      .float-right
        =link_to "Back", admin_subscriptions_path, class: 'm-3 btn-info btn-lg'

app/views/layouts/admin.html.haml
<!DOCTYPE html>
%html
  %head
    %title HamlPractice
    = csrf_meta_tags
    = csp_meta_tag
    %meta{:charset => "utf-8"}/
    %title TRY
    %meta{:name => "description", :content => "Ogusu"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Sawarabi+Mincho&display=swap", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/earlyaccess/hannari.css" , :rel => "stylesheet"}/
    %link{:rel => "stylesheet", :href => "styles.css"}/


    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %nav.navbar.navbar-expand-lg.navbar-light.bg-light
      =link_to "Admin Page" ,admin_root_path, class: "navbar-brand"
      .collapse.navbar-collapse#navbarNavAltMarkup
        .navbar-nav
          =link_to 'subscription', admin_subscriptions_path, class: "nav-item nav-link"
    .container-fluid.p-5
      = yield

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HamlPractice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <title>TRY</title>
    <meta name="description" content="Ogusu">
    <link href="https://fonts.googleapis.com/css?family=Sawarabi+Mincho&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/earlyaccess/hannari.css" rel="stylesheet">
    <link rel="stylesheet" href="styles.css">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <div class="header">
      <div class="logo">
      <p>LOGO</P>
      </div>
      <div class="header-menu">
        <p class="header-menu1"><a href="#1">商品・価格</a></p>
        <p class="header-menu2"><a href="#2">宅配ガイド・手数料</a></p>
        <p class="header-menu3"><a href="#3">おためしセット</a></p>
        <p class="header-menu4"><a href="#4">加入申し込み・資料請求</a></p>
        <p class="header-menu5"><a href="#5">ログイン</a></p>
      </div>
     </div>

   <div class="app">
    <%= yield %>
   </div>
  </body>
</html>

app/views/pages/_about.html.haml
.lg-flex-col-container
  %h3{style: "width: 100%"}
    %span{:style => "line-height:200%;"}
      %link{:href => "https://fonts.googleapis.com/css?family=Kalam:300&display=swap", :rel => "stylesheet"}/
      ="About"
  %p{style: "margin: 0"}
    ="様々な種類のおやつを"
    %br
    ="食べきりサイズでお届けします。"
    %br
    ="マイページでリクエストや評価をするほど自分好みに。"

app/views/pages/_how_to_order.html.haml
.lg-flex-col-container
  %h3{style: "width: 100%"}
    ="コースの種類"
  %p{style: "margin: 0"}
    ="コースについての"
    %br
    ="説明をここに記入する"

app/views/pages/_line.html.haml
.lg-flex-col-container
  %h3{style: "width: 100%"}
    ="something"

app/views/pages/_points.html.haml
.points
  .point
    .point1-photo
      .point1-text
        %h3{style: "width: 100%"}
          %span{:style => "line-height:200%;"}
            ="POINT1"
        %p{style: "margin: 0"}
        ="様々な種類のおやつを、"
        %br
        ="おやつ診断をしてご注文いただくと、"
        %br
        ="定期的にBOXをポストにお届けします。"
  .point
    .point2-photo
      .point2-text
        %h3{style: "width: 100%"}
          %span{:style => "line-height:200%;"}
            ="POINT2"
        %p{style: "margin: 0"}
        ="様々な種類のおやつを、"
        %br
        ="おやつ診断をしてご注文いただくと、"
        %br
        ="定期的にBOXをポストにお届けします。"
  .point
    .point3-photo
      .point3-text
        %h3{style: "width: 100%"}
          %span{:style => "line-height:200%;"}
            ="POINT3"
        %p{style: "margin: 0"}
        ="様々な種類のおやつを、"
        %br
        ="おやつ診断をしてご注文いただくと、"
        %br
        ="定期的にBOXをポストにお届けします。"

app/views/pages/_subscriptions.html.haml
-images = ["https://snaq.me/wp-content/uploads/2019/02/about_snaq.me3_.jpg", "https://snaq.me/wp-content/uploads/2019/02/about_snaq.me1_.jpg", "https://snaq.me/wp-content/uploads/2019/02/about_snaq.me2_.jpg"]
.about-card-group
  -Subscription.all.each_with_index do |subscription, i|
    .item
      .item-title
        =subscription.name
      .item-photo
        %img{src: images[i], alt: "plan-image#{i.to_s}", class: "item-photo"}
      .item-text
        =subscription.tagline
        %br
        =subscription.description
        %br
        ="Price: #{subscription.price} Quantity:#{subscription.quantity}"

app/views/pages/home.html.haml
.hero-image
= render 'about'
= render 'points'
= render 'how_to_order'
= render 'subscriptions'
= render 'line'

app/views/temp/index.html.haml
.subscription
  -@subscriptions.each do |subscription|
    .plan
      .plan-tagline
        %h2
          =subscription.tagline
      .plan-container
        .container-detail1
          =subscription.name
        .container-detail2
          .box1
            =subscription.description
          .box2
            =subscription.quantity
      .plan-example
        %h3
          text
      .plan-photo
      .plan-explain
      .plan-button